### ISSUE TITLE
invalid use of incomplete type ‘class QButtonGroup’

### ISSUE THREAD

**Issue by braegel** [dl1ksv/linpsk#3] opened 2018-11-19 10:53 UTC
Sadly i cannot compile. 

Build.log:
[linkpsk.log](https://github.com/dl1ksv/linpsk/files/2594938/linkpsk.log)

**Comment by dl1ksv** [comment] 2018-11-19 15:47
Thank you for your report.
It's interesting, as I can't reproduce this error. I think it's an Qt problem.
Which version of Qt and which linux distro are you using ?
Here is my one:
qmake -v
QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu 

on Ubuntu 18.04.

In my ui_modemenu.h there is

#include <QtWidgets/QButtonGroup>

Can you check ui_modemenu.h in your build directory ?
Including QButtonGroup does no harm, but I 'd like to find the reason for your problem and fix this.

**Comment by braegel** [comment] 2018-11-19 20:09
% qmake -v
QMake version 3.1
Using Qt version 5.11.1 in /usr/lib64

  % cat /proc/version
Linux version 4.14.65-gentoo (root@hp420) (gcc version 7.3.0 (Gentoo 7.3.0-r3 p1.4)) #4 SMP PREEMPT Thu Nov 1 21:39:21 CET 2018

**Comment by dl1ksv** [comment] 2018-11-20 20:51
I can confirm this bug on gentoo with Qt5.11.1. This bug remains after updating to QT5.11.2.

As I think that it will last until it's fixed in qt I modified the appropiate header file.
Now it again compiles on gentoo.
Thanks for your report.

**Closed as completed** 2018-11-26 09:41 UTC
